include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/generated_plugin_registrant.dart'
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    override_on_non_overriding_member: error
    always_use_package_imports: error
    sort_pub_dependencies: warning

linter:
  rules:
    always_use_package_imports: true
    sort_pub_dependencies: true
