name: flutter_tools
description: Common useful utilities
version: 0.0.1
homepage: https://github.com/Afflya/flutter_tools

publish_to: none

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.16.3"

dependencies:
  collection: '>=1.17.1'
  convert: '>=3.1.1-0'
  flutter:
    sdk: flutter
  flutter_svg: '>=2.0.9'
  http: '>=1.1.2'
  logger: '>=2.0.2+1'
  shared_preferences: '>=2.2.2'

dev_dependencies:
  flutter_lints: '>=3.0.1-0 <4.0.0'
  flutter_test:
    sdk: flutter

flutter:
