name: flutter_tools
description: Common useful utilities
version: 0.0.1
homepage: https://github.com/Afflya/flutter_tools

publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.4"

dependencies:
  collection: '>=1.15.0'
  dartz: '>=0.10.0'
  diffutil_dart: '>=2.0.0-0 <3.1.0'
  equatable: '>=2.0.0-0 <2.1.0'
  flutter:
    sdk: flutter
  flutter_svg: '>=1.0.0'
  http: '>=0.13.4'
  logger: '>=1.1.0'
  shared_preferences: '>=2.0.9'
  uuid: '>=3.0.5'

dev_dependencies:
  build_runner: '>=2.2.0'
  flutter_test:
    sdk: flutter
  lint: '>=1.5.3-0 <1.6.0'

flutter:
