name: flutter_tools
description: Common useful utilities
version: 0.0.1
homepage: https://github.com/Afflya/flutter_tools

publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  collection: '>=1.17.1'
  convert: '>=3.1.1-0'
  flutter:
    sdk: flutter
  flutter_svg: '>=2.0.5'
  http: '>=0.13.6'
  logger: '>=1.1.0'
  shared_preferences: '>=2.1.1'

dev_dependencies:
  flutter_lints: '>=2.0.1-0 <3.0.0'
  flutter_test:
    sdk: flutter

flutter:
